#!/usr/bin/env bash
# configure-haproxy-forwarder.sh — Install and configure HAProxy for IBM Cloud ACP cluster access
# Usage: sudo ./hack/configure-haproxy-forwarder.sh
#
# Required environment variables (set in hack/env.sh):
#   CLUSTER_NAME   - OpenShift cluster name (e.g., "acp")
#   BASE_DOMAIN    - Base DNS domain (e.g., "example.com")
#   API_VIP        - Internal API VIP (default: 192.168.50.253)
#   INGRESS_VIP    - Internal Ingress VIP (default: 192.168.50.252)
#
# IMPORTANT — IBM Cloud NAT requirement:
#   HAProxy MUST bind to 0.0.0.0, NOT to the private IP (10.241.64.5).
#   IBM Cloud's NAT translates the public IP to the private IP before traffic
#   reaches eth0. A process bound to 10.241.64.5 only will NOT receive this traffic.
#
# Ports forwarded:
#   6443  → API VIP:6443   (Kubernetes API)
#   22623 → API VIP:22623  (Machine Config Server)
#   80    → Ingress VIP:80 (HTTP application routes)
#   443   → Ingress VIP:443 (HTTPS application routes)
#   8404  → HAProxy stats dashboard (HTTP, optional)
#
# Reference: https://tosin2013.github.io/openshift-agent-install/ibm-cloud-deployment.html

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
die()   { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "This script must be run as root (sudo $0)"

: "${CLUSTER_NAME:?ERROR: CLUSTER_NAME is not set. Source hack/env.sh first.}"
: "${BASE_DOMAIN:?ERROR: BASE_DOMAIN is not set. Source hack/env.sh first.}"
API_VIP="${API_VIP:-192.168.50.253}"
INGRESS_VIP="${INGRESS_VIP:-192.168.50.252}"

info "Configuring HAProxy for cluster: ${CLUSTER_NAME}.${BASE_DOMAIN}"
info "  API VIP     : ${API_VIP}"
info "  Ingress VIP : ${INGRESS_VIP}"
info "  Binding to  : 0.0.0.0 (required for IBM Cloud NAT)"

# ── Install HAProxy ────────────────────────────────────────────────────────────
if ! rpm -q haproxy &>/dev/null; then
    info "Installing haproxy..."
    dnf install -y haproxy
fi

# ── Backup existing config ─────────────────────────────────────────────────────
if [[ -f /etc/haproxy/haproxy.cfg ]]; then
    cp /etc/haproxy/haproxy.cfg "/etc/haproxy/haproxy.cfg.bak.$(date +%Y%m%d%H%M%S)"
    info "  Existing config backed up"
fi

# ── Write HAProxy config ───────────────────────────────────────────────────────
cat > /etc/haproxy/haproxy.cfg <<EOF
# HAProxy configuration for ACP OpenShift cluster
# Cluster: ${CLUSTER_NAME}.${BASE_DOMAIN}
# Generated by hack/configure-haproxy-forwarder.sh
#
# CRITICAL: All frontends bind to 0.0.0.0 — IBM Cloud NAT requirement.
# If HAProxy is bound to the private IP only, external traffic will NOT arrive.

global
    log         /dev/log local0
    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     50000
    user        haproxy
    group       haproxy
    daemon

defaults
    mode                    tcp
    log                     global
    option                  tcplog
    option                  dontlognull
    option                  redispatch
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          4h
    timeout server          4h
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 3000

# ── Kubernetes API Server (6443) ──────────────────────────────────────────────
frontend api-server
    bind 0.0.0.0:6443
    mode tcp
    option tcplog
    default_backend api-server-backend

backend api-server-backend
    mode tcp
    balance roundrobin
    option tcp-check
    server api-vip ${API_VIP}:6443 check

# ── Machine Config Server (22623) ─────────────────────────────────────────────
frontend machine-config-server
    bind 0.0.0.0:22623
    mode tcp
    option tcplog
    default_backend machine-config-server-backend

backend machine-config-server-backend
    mode tcp
    balance roundrobin
    server mcs-vip ${API_VIP}:22623 check

# ── HTTP Ingress (80) ──────────────────────────────────────────────────────────
frontend http-ingress
    bind 0.0.0.0:80
    mode tcp
    option tcplog
    default_backend http-ingress-backend

backend http-ingress-backend
    mode tcp
    balance roundrobin
    server ingress-http ${INGRESS_VIP}:80 check

# ── HTTPS Ingress (443) ────────────────────────────────────────────────────────
frontend https-ingress
    bind 0.0.0.0:443
    mode tcp
    option tcplog
    default_backend https-ingress-backend

backend https-ingress-backend
    mode tcp
    balance roundrobin
    server ingress-https ${INGRESS_VIP}:443 check

# ── HAProxy Stats Dashboard (8404) ────────────────────────────────────────────
listen stats
    bind 0.0.0.0:8404
    mode http
    stats enable
    stats uri /
    stats refresh 30s
    stats show-legends
    stats show-node
    # Restrict to trusted IPs in production; open for lab
    # acl trusted src 10.0.0.0/8
    # stats http-request allow if trusted
EOF

info "  HAProxy config written to /etc/haproxy/haproxy.cfg"

# ── SELinux: allow HAProxy to connect to any port ─────────────────────────────
if command -v setsebool &>/dev/null; then
    setsebool -P haproxy_connect_any 1 2>/dev/null || warn "Could not set SELinux boolean haproxy_connect_any"
    info "  SELinux: haproxy_connect_any enabled"
fi

# ── Open firewalld ports ───────────────────────────────────────────────────────
if systemctl is-active firewalld &>/dev/null; then
    info "Opening firewalld ports for cluster access..."
    for port in 6443 22623 80 443 8404; do
        firewall-cmd --permanent --add-port="${port}/tcp" 2>/dev/null || true
    done
    firewall-cmd --reload
    info "  Ports 6443, 22623, 80, 443, 8404/tcp opened"
fi

# ── Enable and start HAProxy ───────────────────────────────────────────────────
info "Enabling and starting HAProxy..."
systemctl enable haproxy
systemctl restart haproxy

sleep 2
if systemctl is-active haproxy &>/dev/null; then
    info "  HAProxy is running"
else
    die "HAProxy failed to start. Check: journalctl -u haproxy -n 50"
fi

# ── Verify port bindings ───────────────────────────────────────────────────────
info "Verifying HAProxy port bindings..."
echo ""
ss -tlnp | grep haproxy | awk '{print "  " $4}' | sort -u
echo ""

# Confirm 0.0.0.0 binding (not just private IP)
if ss -tlnp | grep haproxy | grep -q "0.0.0.0"; then
    info "  Confirmed: HAProxy is bound to 0.0.0.0 (IBM Cloud NAT will work correctly)"
else
    warn "  HAProxy may not be bound to 0.0.0.0. Check /etc/haproxy/haproxy.cfg"
fi

echo ""
info "HAProxy configuration complete."
info "  Stats dashboard: http://<EXTERNAL_IP>:8404/"
info "  API access     : https://api.${CLUSTER_NAME}.${BASE_DOMAIN}:6443 (after DNS propagates)"
info ""
info "Next: Run ./hack/verify-dns-resolution.sh before deploying VMs"
