#!/usr/bin/env bash
# deploy-kvm-vms.sh — Create KVM VMs for ACP OpenShift cluster on IBM Cloud
# Usage: ./hack/deploy-kvm-vms.sh [--config examples/ibm-cloud-active/extra-vars.yml] [--iso /path/to/agent.x86_64.iso]
#
# Required environment variables (set in hack/env.sh):
#   CLUSTER_NAME   - OpenShift cluster name (e.g., "acp")
#   BASE_DOMAIN    - Base DNS domain
#   EXTERNAL_IP    - IBM Cloud public IP (for DNS gate check)
#
# What this script does:
#   1. Verifies MAC addresses are pre-populated in extra-vars.yml (by generate-kvm-macs.sh)
#   2. Verifies the agent ISO exists (generated by create-installation-media.yml)
#   3. Runs verify-dns-resolution.sh as a hard prerequisite gate
#   4. Creates 3 KVM VMs with explicitly assigned MACs (matching the ISO)
#      - 3 NICs: 1925/1926 VLAN (eth0), isolated bridge (eth1), acp-storage (eth2)
#      - 3 disks: 120 GB OS (vda), 100 GB ODF (vdb), 100 GB ODF (vdc)
#      - All disk images in the 'acp-vms' libvirt storage pool on /dev/vdb
#   5. VMs boot immediately from the ISO with correct networking
#
# Provisioning network auto-detection (VyOS-first):
#   examples/ibm-cloud-active → ibm-cloud-converged  ⟹  PROV_NET=1925 (192.168.50.x)
#   examples/ibm-cloud-active → ibm-cloud-sno        ⟹  PROV_NET=1926 (192.168.51.x)
#   Override: export PROV_NET=<network-name>
#
# VM sizing:
#   vCPUs   : 16 per node
#   RAM     : 48 GB per node  (raised from 32 GB 2026-06-04 — ODF MDS+NooBaa require ~14 GB headroom)
#   Disk OS : 120 GB  (vda)
#   Disk ODF: 100 GB  (vdb, vdc)
#
# MAC address workflow (upstream pattern):
#   1. hack/generate-kvm-macs.sh  → writes MACs into extra-vars.yml
#   2. create-installation-media.yml → embeds those MACs in the agent ISO
#   3. THIS SCRIPT               → creates VMs with those exact MACs
#   VMs boot with MACs that match the ISO → OpenShift installs successfully

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "${SCRIPT_DIR}")"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BOLD='\033[1m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
die()   { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

# ── Parse arguments ────────────────────────────────────────────────────────────
CONFIG="${REPO_ROOT}/examples/ibm-cloud-active/extra-vars.yml"
ISO_PATH=""
VCPUS=16
RAM_MB=49152   # 48 GiB — ODF MDS (6 GiB) + NooBaa DB (4 GiB) require headroom beyond the 32 GiB base OCP footprint
DISK_OS_GB=120
DISK_ODF_GB=100
POOL="acp-vms"
STORAGE_NET="acp-storage"

# Auto-detect provisioning VLAN from the active topology symlink.
# Converged cluster → VLAN 1925 (192.168.50.x)
# SNO cluster       → VLAN 1926 (192.168.51.x)
# Override by setting PROV_NET in the environment.
if [[ -z "${PROV_NET:-}" ]]; then
    ACTIVE_LINK=$(readlink -f "${REPO_ROOT}/examples/ibm-cloud-active" 2>/dev/null || echo "")
    if [[ "$ACTIVE_LINK" == *"sno"* ]]; then
        PROV_NET="1926"
    else
        PROV_NET="1925"   # default: converged
    fi
fi

while [[ $# -gt 0 ]]; do
    case "$1" in
        --config) CONFIG="$2"; shift 2;;
        --iso)    ISO_PATH="$2"; shift 2;;
        --vcpus)  VCPUS="$2"; shift 2;;
        --ram)    RAM_MB="$2"; shift 2;;
        --sno)    VCPUS=16; RAM_MB=32768;;  # SNO stays at 32 GiB (no ODF MDS/NooBaa)
        *) die "Unknown argument: $1";;
    esac
done

: "${CLUSTER_NAME:?ERROR: CLUSTER_NAME is not set. Source hack/env.sh first.}"
: "${EXTERNAL_IP:?ERROR: EXTERNAL_IP is not set. Source hack/env.sh first.}"

# ── Validate MAC addresses are pre-generated ───────────────────────────────────
# MACs must be filled by generate-kvm-macs.sh before this script runs.
if grep -q "FILL_FROM_deploy-kvm-vms.sh" "${CONFIG}" 2>/dev/null; then
    die "MAC address placeholders still present in ${CONFIG}
  Run first: ./hack/generate-kvm-macs.sh ${CONFIG}
  This pre-generates MACs so the ISO and VMs use the same addresses."
fi
info "MAC addresses verified: all placeholders filled in ${CONFIG}"

# ── Read per-node MACs from extra-vars.yml ─────────────────────────────────────
# Returns the Nth (0-indexed) mac_address for the named node in the YAML.
# Scopes search to the control_nodes: section so interface names (eth0/eth1/eth2)
# and other YAML sections (dns.acls etc.) do not interfere.
_get_mac() {
    local node_name="$1"
    local iface_index="$2"
    python3 - "${CONFIG}" "${node_name}" "${iface_index}" <<'PYEOF'
import sys, re
config_file, node_name, iface_index = sys.argv[1], sys.argv[2], int(sys.argv[3])
with open(config_file) as f:
    content = f.read()
# Extract the control_nodes: block (indented under openshift:)
cn_match = re.search(r'control_nodes:(.*?)(?=\n  [a-zA-Z]|\Z)', content, re.DOTALL)
if not cn_match:
    print("unknown"); sys.exit(1)
cn_section = cn_match.group(1)
# Within that block, find this node's sub-section.
# Stop at the next node-level entry (4-space "- name:") or end of section.
pattern = r'-\s+name:\s+' + re.escape(node_name) + r'\b(.*?)(?=\n\s{4}-\s+name:\s|\Z)'
match = re.search(pattern, cn_section, re.DOTALL)
if not match:
    print("unknown"); sys.exit(1)
macs = re.findall(r'mac_address:\s*(\S+)', match.group(0))
if iface_index >= len(macs):
    print("unknown"); sys.exit(1)
print(macs[iface_index])
PYEOF
}

# ── Find the agent ISO ─────────────────────────────────────────────────────────
if [[ -z "${ISO_PATH}" ]]; then
    KUBECONFIG_DIR="${HOME}/cluster_${CLUSTER_NAME}/install"
    ISO_PATH="${KUBECONFIG_DIR}/agent.x86_64.iso"
fi

if [[ ! -f "${ISO_PATH}" ]]; then
    die "Agent ISO not found at ${ISO_PATH}
  Run: ansible-playbook playbooks/create-installation-media.yml \\
         -i examples/ibm-cloud-active/inventory.yml \\
         -e @${CONFIG}
  Then re-run this script."
fi

# The qemu process runs as the 'qemu' user and cannot access files under /home/<user>
# unless the home directory is world-executable. Copy the ISO to the libvirt images
# directory which is always accessible to the qemu user.
QEMU_ISO_DIR="/var/lib/libvirt/images"
QEMU_ISO_PATH="${QEMU_ISO_DIR}/agent-$(basename "${CLUSTER_NAME}").x86_64.iso"
if [[ ! -f "${QEMU_ISO_PATH}" ]] || \
   [[ "${ISO_PATH}" -nt "${QEMU_ISO_PATH}" ]]; then
    info "Copying ISO to qemu-accessible location: ${QEMU_ISO_PATH}"
    sudo cp "${ISO_PATH}" "${QEMU_ISO_PATH}"
    sudo chmod 644 "${QEMU_ISO_PATH}"
fi
info "Agent ISO (qemu path): ${QEMU_ISO_PATH}"

# ── Mandatory DNS verification gate ───────────────────────────────────────────
echo ""
echo -e "${BOLD}Running DNS verification gate...${NC}"
"${SCRIPT_DIR}/verify-dns-resolution.sh" || {
    echo ""
    die "DNS verification failed. Fix DNS before deploying VMs."
}
echo ""

# ── Determine VM names from config ────────────────────────────────────────────
# Extract node names from the control_nodes: section only.
# A plain grep on "- name:" would also pick up interface names (eth0/eth1/eth2)
# and dns.acls entries, so we scope the search with Python.
mapfile -t NODE_NAMES < <(
    python3 - "${CONFIG}" <<'PYEOF'
import sys, re
with open(sys.argv[1]) as f:
    content = f.read()
cn = re.search(r'control_nodes:(.*?)(?=\n  [a-zA-Z]|\Z)', content, re.DOTALL)
if cn:
    # Node-level names are at 4-space indent: "    - name: control-X"
    print('\n'.join(re.findall(r'^\s{4}-\s+name:\s+(\S+)', cn.group(1), re.MULTILINE)))
PYEOF
)
[[ ${#NODE_NAMES[@]} -gt 0 ]] || NODE_NAMES=("control-0" "control-1" "control-2")

info "VMs to create: ${NODE_NAMES[*]}"
info "  Provisioning net : ${PROV_NET} (converged=1925, SNO=1926)"
info "  Storage net      : ${STORAGE_NET}"
info "  vCPUs per VM     : ${VCPUS}"
info "  RAM per VM       : $((RAM_MB / 1024)) GB"
info "  OS disk          : ${DISK_OS_GB} GB"
info "  ODF disks        : 2 × ${DISK_ODF_GB} GB"
info "  Storage pool     : ${POOL}"
info "  MACs             : pre-assigned from ${CONFIG}"

# ── Create isolated bridge for eth1 ───────────────────────────────────────────
if ! sudo virsh net-info acp-isolated &>/dev/null; then
    info "Creating isolated acp-isolated network for eth1..."
    cat > /tmp/libvirt-net-isolated.xml <<'EOF'
<network>
  <name>acp-isolated</name>
  <bridge name='virbr-acp1' stp='on' delay='0'/>
</network>
EOF
    sudo virsh net-define /tmp/libvirt-net-isolated.xml
    sudo virsh net-autostart acp-isolated
    sudo virsh net-start acp-isolated
    rm -f /tmp/libvirt-net-isolated.xml
fi

# ── Create VMs with pre-defined MACs ──────────────────────────────────────────
for NODE in "${NODE_NAMES[@]}"; do
    if sudo virsh dominfo "${NODE}" &>/dev/null; then
        warn "VM '${NODE}' already exists — skipping."
        warn "  To recreate: sudo virsh destroy ${NODE} && sudo virsh undefine ${NODE} --remove-all-storage"
        continue
    fi

    # Read the three MACs for this node from extra-vars.yml
    MAC_ETH0=$(_get_mac "${NODE}" 0)
    MAC_ETH1=$(_get_mac "${NODE}" 1)
    MAC_ETH2=$(_get_mac "${NODE}" 2)

    info "Creating VM: ${NODE}"
    info "  eth0 (${PROV_NET})   MAC: ${MAC_ETH0}"
    info "  eth1 (isolated) MAC: ${MAC_ETH1}"
    info "  eth2 (storage)  MAC: ${MAC_ETH2}"

    # Create disk volumes in the storage pool
    sudo virsh vol-create-as "${POOL}" "${NODE}-os.qcow2"   "${DISK_OS_GB}G"  --format qcow2
    sudo virsh vol-create-as "${POOL}" "${NODE}-odf1.qcow2" "${DISK_ODF_GB}G" --format qcow2
    sudo virsh vol-create-as "${POOL}" "${NODE}-odf2.qcow2" "${DISK_ODF_GB}G" --format qcow2

    OS_PATH=$(sudo virsh vol-path --pool "${POOL}" "${NODE}-os.qcow2")
    ODF1_PATH=$(sudo virsh vol-path --pool "${POOL}" "${NODE}-odf1.qcow2")
    ODF2_PATH=$(sudo virsh vol-path --pool "${POOL}" "${NODE}-odf2.qcow2")

    # Create the VM, passing explicit MAC addresses so the VM matches the ISO.
    # ISO path must be under /var/lib/libvirt/images/ (qemu user needs read access).
    # Flags aligned with upstream deploy-on-kvm.sh:
    #   No --boot flag: let virt-install assign per-device boot orders, then fix them below.
    #   on_reboot=restart — patched via virsh define; virt-install 5.x ignores --events
    #   --os-variant fedora-coreos-stable — correct variant for RHCOS nodes
    #   --memballoon none, --features kvm_hidden=on — upstream perf/compat flags
    sudo virt-install \
        --name "${NODE}" \
        --vcpus "${VCPUS}" \
        --memory "${RAM_MB}" \
        --cpu host-passthrough \
        --memballoon none \
        --features kvm_hidden=on \
        --controller type=scsi,model=virtio-scsi \
        --disk "path=${OS_PATH},bus=virtio,cache=none,format=qcow2" \
        --disk "path=${ODF1_PATH},bus=virtio,cache=none,format=qcow2" \
        --disk "path=${ODF2_PATH},bus=virtio,cache=none,format=qcow2" \
        --network "network=${PROV_NET},model=virtio,mac=${MAC_ETH0}" \
        --network "network=acp-isolated,model=virtio,mac=${MAC_ETH1}" \
        --network "network=${STORAGE_NET},model=virtio,mac=${MAC_ETH2}" \
        --cdrom "${QEMU_ISO_PATH}" \
        --os-variant "fedora-coreos-stable" \
        --graphics "vnc,listen=0.0.0.0,defaultMode=insecure" \
        --autostart \
        --noautoconsole \
        --wait 0

    # Patch persistent XML for two critical settings (virt-install 5.x ignores both):
    #
    # 1. on_reboot=restart — agent ISO reboots each node after writing RHCOS to disk;
    #    without this the VM is destroyed on reboot, killing the install.
    #
    # 2. Boot order — virt-install with --cdrom assigns CDROM boot order=1 and disk
    #    order=2, which causes VMs to boot back into the ISO after RHCOS is written.
    #    Correct order: disk=1, cdrom=2.
    #    SeaBIOS gracefully falls through to cdrom (ISO) on first boot because vda is
    #    empty and not yet bootable. After RHCOS is written, vda is bootable first.
    sudo virsh dumpxml "${NODE}" > /tmp/${NODE}-patch.xml
    # Fix on_reboot
    sed -i 's|<on_reboot>destroy</on_reboot>|<on_reboot>restart</on_reboot>|g' /tmp/${NODE}-patch.xml
    # Fix boot order: swap disk (vda/virtio-disk0) to order=1, cdrom (sda) to order=2.
    # The XML has exactly two boot order entries: one on vda and one on sda.
    # Use Python to reliably swap them without brittle regex on adjacent tags.
    python3 - /tmp/${NODE}-patch.xml <<'PYEOF'
import sys, re
path = sys.argv[1]
xml = open(path).read()

# Find all boot order values
orders = re.findall(r"<boot order='(\d+)'/>", xml)
if len(orders) >= 2:
    # Find the cdrom disk target (sda) and virtio disk target (vda)
    # Strategy: find the sda block and set its boot order to 2, vda to 1
    # Replace first occurrence (vda block): set to order='1'
    # Replace second occurrence (sda/cdrom block): set to order='2'
    count = [0]
    def replacer(m):
        count[0] += 1
        if count[0] == 1:
            return "<boot order='1'/>"   # vda — disk first
        elif count[0] == 2:
            return "<boot order='2'/>"   # sda — cdrom fallback
        return m.group(0)
    xml = re.sub(r"<boot order='\d+'/>", replacer, xml)
    open(path, 'w').write(xml)
    print(f"  Boot order patched: vda=1 (disk first), sda=2 (cdrom fallback)")
else:
    print(f"  Warning: expected 2 boot order entries, found {len(orders)} — skipping boot order patch")
PYEOF
    sudo virsh define /tmp/${NODE}-patch.xml >/dev/null
    rm -f /tmp/${NODE}-patch.xml

    info "  ${NODE} created — boot order: vda=1 (disk) sda=2 (ISO fallback), on_reboot=restart"
done

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}═══════════════════════════════════════════════════════${NC}"
echo -e "${BOLD}  VMs Created — OpenShift Installation Starting        ${NC}"
echo -e "${BOLD}═══════════════════════════════════════════════════════${NC}"
echo ""
info "VM status:"
sudo virsh list --all 2>/dev/null | grep -E "Name|$(IFS='|'; echo "${NODE_NAMES[*]}")" || sudo virsh list --all
echo ""
info "VMs are booting from the agent ISO."
info "MACs in the ISO match the VM network interfaces — no manual entry needed."
echo ""
info "Monitor installation:"
info "  export KUBECONFIG=~/cluster_${CLUSTER_NAME}/install/auth/kubeconfig"
info "  openshift-install agent wait-for install-complete \\"
info "    --dir ~/cluster_${CLUSTER_NAME}/install --log-level=info"
echo ""
